apiVersion: v1
kind: DeploymentConfig
metadata:
  name: inventory-database
  labels:
    app: inventory-database
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - inventory-database
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'postgresql:9.2'
  replicas: 1
  test: false
  selector:
    app: inventory-database
    deploymentconfig: inventory-database
  template:
    metadata:
      labels:
        app: inventory-database
        deploymentconfig: inventory-database
      annotations:
        openshift.io/container.inventory-database.image.entrypoint: '["container-entrypoint","run-postgresql"]'
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: inventory-database-volume-1
          emptyDir: {}
      containers:
        - name: inventory-database
          image: openshift/postgresql-92-centos7
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_DATABASE
              value: inventory
            - name: POSTGRESQL_PASSWORD
              value: password
            - name: POSTGRESQL_USER
              value: swarm
          volumeMounts:
            - name: inventory-database-volume-1
              mountPath: /var/lib/pgsql/data
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
